create table author (
    id          bigint generated by default as identity primary key,
    name        varchar(120) not null unique,
    bio         text         not null default '',
    x_link      varchar(255),
    fb_link     varchar(255),
    insta_link  varchar(255),
    pfp_link    varchar(255),
    created_at  timestamptz,
    updated_at  timestamptz
);

create table post (
    id            bigint generated by default as identity primary key,
    slug          varchar(200) not null unique,
    title         varchar(300) not null,
    excerpt       text         not null default '',
    author        varchar(120) not null default '',
    cover_image   varchar(255),
    published_on  date         not null,
    content       text         not null default '',   -- raw markdown (body)
    content_html  text         not null default '',   -- rendered HTML
    published     boolean      not null default true,
    created_at    timestamptz,
    updated_at    timestamptz
);
create index idx_post_pub on post (published, published_on desc);

create table post_tags (
    post_id  bigint       not null references post (id) on delete cascade,
    tag      varchar(80)  not null
);
create index idx_post_tags_post on post_tags (post_id);

create table comment (
    id          bigint generated by default as identity primary key,
    post_slug   varchar(200) not null,
    name        varchar(120) not null,
    email       varchar(200) not null,
    body        text         not null,
    created_at  timestamptz,
    updated_at  timestamptz
);
create index idx_comment_post on comment (post_slug, created_at);

create table subscription (
    id          bigint generated by default as identity primary key,
    email       varchar(200) not null unique,
    created_at  timestamptz,
    updated_at  timestamptz
);
